// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlinVersion}"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.navigationVersion}"
        classpath "com.google.gms:google-services:${Versions.googleServicesVersion}"
        classpath "com.google.firebase:firebase-crashlytics-gradle:${Versions.crashlyticsGradleVersion}"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://repository.map.naver.com/archive/maven'
            content {
                includeGroup 'com.naver.maps'
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    minSdkVersion = 23
    targetSdkVersion = 36
    compileSdkVersion = 36
}
