package dev.kxxcn.maru.view.present

import dev.kxxcn.maru.R
import dev.kxxcn.maru.data.Present

enum class PresentFilterType(
    val items: List<Present>
) {

    /**
     * 반지
     */
    RING(
        listOf(
            Present(
                R.string.present_ring_short_thick_title,
                R.string.present_ring_short_thick_content,
                listOf(
                    R.drawable.img_ring_short_thick_1,
                    R.drawable.img_ring_short_thick_2,
                    R.drawable.img_ring_short_thick_3,
                    R.drawable.img_ring_short_thick_4,
                    R.drawable.img_ring_short_thick_5,
                    R.drawable.img_ring_short_thick_6,
                    R.drawable.img_ring_short_thick_7,
                    R.drawable.img_ring_short_thick_8,
                    R.drawable.img_ring_short_thick_9,
                    R.drawable.img_ring_short_thick_10
                )
            ),
            Present(
                R.string.present_ring_short_thin_title,
                R.string.present_ring_short_thin_content,
                listOf(
                    R.drawable.img_ring_short_thin_1,
                    R.drawable.img_ring_short_thin_2,
                    R.drawable.img_ring_short_thin_3,
                    R.drawable.img_ring_short_thin_4,
                    R.drawable.img_ring_short_thin_5,
                    R.drawable.img_ring_short_thin_6,
                    R.drawable.img_ring_short_thin_7,
                    R.drawable.img_ring_short_thin_8,
                    R.drawable.img_ring_short_thin_9,
                    R.drawable.img_ring_short_thin_10
                )
            ),
            Present(
                R.string.present_ring_long_thick_title,
                R.string.present_ring_long_thick_content,
                listOf(
                    R.drawable.img_ring_long_thick_1,
                    R.drawable.img_ring_long_thick_2,
                    R.drawable.img_ring_long_thick_3,
                    R.drawable.img_ring_long_thick_4,
                    R.drawable.img_ring_long_thick_5,
                    R.drawable.img_ring_long_thick_6,
                    R.drawable.img_ring_long_thick_7,
                    R.drawable.img_ring_long_thick_8,
                    R.drawable.img_ring_long_thick_9,
                    R.drawable.img_ring_long_thick_10
                )
            ),
            Present(
                R.string.present_ring_long_thin_title,
                R.string.present_ring_long_thin_content,
                listOf(
                    R.drawable.img_ring_long_thin_1,
                    R.drawable.img_ring_long_thin_2,
                    R.drawable.img_ring_long_thin_3,
                    R.drawable.img_ring_long_thin_4,
                    R.drawable.img_ring_long_thin_5,
                    R.drawable.img_ring_long_thin_6,
                    R.drawable.img_ring_long_thin_7,
                    R.drawable.img_ring_long_thin_8,
                    R.drawable.img_ring_long_thin_9,
                    R.drawable.img_ring_long_thin_10
                )
            )
        )
    ),

    /**
     * 드레스
     */
    DRESS(
        listOf(
            Present(
                R.string.present_dress_a_title,
                R.string.present_dress_a_content,
                listOf(
                    R.drawable.img_a_dress_1,
                    R.drawable.img_a_dress_2,
                    R.drawable.img_a_dress_3,
                    R.drawable.img_a_dress_4,
                    R.drawable.img_a_dress_5,
                    R.drawable.img_a_dress_6,
                    R.drawable.img_a_dress_7,
                    R.drawable.img_a_dress_8,
                    R.drawable.img_a_dress_9,
                    R.drawable.img_a_dress_10
                )
            ),
            Present(
                R.string.present_dress_bell_title,
                R.string.present_dress_bell_content,
                listOf(
                    R.drawable.img_bell_dress_1,
                    R.drawable.img_bell_dress_2,
                    R.drawable.img_bell_dress_3,
                    R.drawable.img_bell_dress_4,
                    R.drawable.img_bell_dress_5,
                    R.drawable.img_bell_dress_6,
                    R.drawable.img_bell_dress_7,
                    R.drawable.img_bell_dress_8,
                    R.drawable.img_bell_dress_9,
                    R.drawable.img_bell_dress_10
                )
            ),
            Present(
                R.string.present_dress_mermaid_title,
                R.string.present_dress_mermaid_content,
                listOf(
                    R.drawable.img_mermaid_dress_1,
                    R.drawable.img_mermaid_dress_2,
                    R.drawable.img_mermaid_dress_3,
                    R.drawable.img_mermaid_dress_4,
                    R.drawable.img_mermaid_dress_5,
                    R.drawable.img_mermaid_dress_6,
                    R.drawable.img_mermaid_dress_7,
                    R.drawable.img_mermaid_dress_8,
                    R.drawable.img_mermaid_dress_9,
                    R.drawable.img_mermaid_dress_10
                )
            ),
            Present(
                R.string.present_dress_empire_title,
                R.string.present_dress_empire_content,
                listOf(
                    R.drawable.img_empire_dress_1,
                    R.drawable.img_empire_dress_2,
                    R.drawable.img_empire_dress_3,
                    R.drawable.img_empire_dress_4,
                    R.drawable.img_empire_dress_5,
                    R.drawable.img_empire_dress_6,
                    R.drawable.img_empire_dress_7,
                    R.drawable.img_empire_dress_8,
                    R.drawable.img_empire_dress_9,
                    R.drawable.img_empire_dress_10
                )
            ),
            Present(
                R.string.present_dress_princess_title,
                R.string.present_dress_princess_content,
                listOf(
                    R.drawable.img_princess_dress_1,
                    R.drawable.img_princess_dress_2,
                    R.drawable.img_princess_dress_3,
                    R.drawable.img_princess_dress_4,
                    R.drawable.img_princess_dress_5,
                    R.drawable.img_princess_dress_6,
                    R.drawable.img_princess_dress_7,
                    R.drawable.img_princess_dress_8,
                    R.drawable.img_princess_dress_9,
                    R.drawable.img_princess_dress_10
                )
            )
        )
    ),

    /**
     * 턱시도
     */
    TUXEDO(
        listOf(
            Present(
                R.string.present_tuxedo_short_thick_title,
                R.string.present_tuxedo_short_thick_content,
                listOf(
                    R.drawable.img_tuxedo_short_thick_1,
                    R.drawable.img_tuxedo_short_thick_2,
                    R.drawable.img_tuxedo_short_thick_3,
                    R.drawable.img_tuxedo_short_thick_4,
                    R.drawable.img_tuxedo_short_thick_5,
                    R.drawable.img_tuxedo_short_thick_6,
                    R.drawable.img_tuxedo_short_thick_7,
                    R.drawable.img_tuxedo_short_thick_8,
                    R.drawable.img_tuxedo_short_thick_9,
                    R.drawable.img_tuxedo_short_thick_10
                )
            ),
            Present(
                R.string.present_tuxedo_short_thin_title,
                R.string.present_tuxedo_short_thin_content,
                listOf(
                    R.drawable.img_tuxedo_short_thin_1,
                    R.drawable.img_tuxedo_short_thin_2,
                    R.drawable.img_tuxedo_short_thin_3,
                    R.drawable.img_tuxedo_short_thin_4,
                    R.drawable.img_tuxedo_short_thin_5,
                    R.drawable.img_tuxedo_short_thin_6,
                    R.drawable.img_tuxedo_short_thin_7,
                    R.drawable.img_tuxedo_short_thin_8,
                    R.drawable.img_tuxedo_short_thin_9,
                    R.drawable.img_tuxedo_short_thin_10
                )
            ),
            Present(
                R.string.present_tuxedo_long_thick_title,
                R.string.present_tuxedo_long_thick_content,
                listOf(
                    R.drawable.img_tuxedo_long_thick_1,
                    R.drawable.img_tuxedo_long_thick_2,
                    R.drawable.img_tuxedo_long_thick_3,
                    R.drawable.img_tuxedo_long_thick_4,
                    R.drawable.img_tuxedo_long_thick_5,
                    R.drawable.img_tuxedo_long_thick_6,
                    R.drawable.img_tuxedo_long_thick_7,
                    R.drawable.img_tuxedo_long_thick_8,
                    R.drawable.img_tuxedo_long_thick_9,
                    R.drawable.img_tuxedo_long_thick_10
                )
            ),
            Present(
                R.string.present_tuxedo_long_thin_title,
                R.string.present_tuxedo_long_thin_content,
                listOf(
                    R.drawable.img_tuxedo_long_thin_1,
                    R.drawable.img_tuxedo_long_thin_2,
                    R.drawable.img_tuxedo_long_thin_3,
                    R.drawable.img_tuxedo_long_thin_4,
                    R.drawable.img_tuxedo_long_thin_5,
                    R.drawable.img_tuxedo_long_thin_6,
                    R.drawable.img_tuxedo_long_thin_7,
                    R.drawable.img_tuxedo_long_thin_8,
                    R.drawable.img_tuxedo_long_thin_9,
                    R.drawable.img_tuxedo_long_thin_10
                )
            )
        )
    ),

    /**
     * 한복
     */
    HANBOK(
        listOf(
            Present(
                R.string.present_hanbok_short_thick_title,
                R.string.present_hanbok_short_thick_content,
                listOf(
                    R.drawable.img_hanbok_short_thick_1,
                    R.drawable.img_hanbok_short_thick_2,
                    R.drawable.img_hanbok_short_thick_3,
                    R.drawable.img_hanbok_short_thick_4,
                    R.drawable.img_hanbok_short_thick_5,
                    R.drawable.img_hanbok_short_thick_6,
                    R.drawable.img_hanbok_short_thick_7,
                    R.drawable.img_hanbok_short_thick_8,
                    R.drawable.img_hanbok_short_thick_9,
                    R.drawable.img_hanbok_short_thick_10
                )
            ),
            Present(
                R.string.present_hanbok_short_thin_title,
                R.string.present_hanbok_short_thin_content,
                listOf(
                    R.drawable.img_hanbok_short_thin_1,
                    R.drawable.img_hanbok_short_thin_2,
                    R.drawable.img_hanbok_short_thin_3,
                    R.drawable.img_hanbok_short_thin_4,
                    R.drawable.img_hanbok_short_thin_5,
                    R.drawable.img_hanbok_short_thin_6,
                    R.drawable.img_hanbok_short_thin_7,
                    R.drawable.img_hanbok_short_thin_8,
                    R.drawable.img_hanbok_short_thin_9,
                    R.drawable.img_hanbok_short_thin_10
                )
            ),
            Present(
                R.string.present_hanbok_long_thick_title,
                R.string.present_hanbok_long_thick_content,
                listOf(
                    R.drawable.img_hanbok_long_thick_1,
                    R.drawable.img_hanbok_long_thick_2,
                    R.drawable.img_hanbok_long_thick_3,
                    R.drawable.img_hanbok_long_thick_4,
                    R.drawable.img_hanbok_long_thick_5,
                    R.drawable.img_hanbok_long_thick_6,
                    R.drawable.img_hanbok_long_thick_7,
                    R.drawable.img_hanbok_long_thick_8,
                    R.drawable.img_hanbok_long_thick_9,
                    R.drawable.img_hanbok_long_thick_10
                )
            ),
            Present(
                R.string.present_hanbok_long_thin_title,
                R.string.present_hanbok_long_thin_content,
                listOf(
                    R.drawable.img_hanbok_long_thin_1,
                    R.drawable.img_hanbok_long_thin_2,
                    R.drawable.img_hanbok_long_thin_3,
                    R.drawable.img_hanbok_long_thin_4,
                    R.drawable.img_hanbok_long_thin_5,
                    R.drawable.img_hanbok_long_thin_6,
                    R.drawable.img_hanbok_long_thin_7,
                    R.drawable.img_hanbok_long_thin_8,
                    R.drawable.img_hanbok_long_thin_9,
                    R.drawable.img_hanbok_long_thin_10
                )
            )
        )
    ),
}
